FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/redis ./cmd/redis/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/redis /app/redis

RUN mkdir -p /app/configs
VOLUME /app/configs

EXPOSE 8028

ENTRYPOINT ["sh", "-c", "if [ -f \"/app/configs/${CONFIG_FILE}\" ]; then ./redis --config /app/configs/${CONFIG_FILE}; else echo \"Error: Config file not found. Please mount your config file to configs/ and set CONFIG_FILE env variable\"; exit 1; fi"]