version: 3

tasks:
  build all:
    aliases:
      - build-all
    cmds:
      - docker build -t zitrax78/breezynotes-gateway --file ./build/gateway/dockerfile .
      - docker build -t zitrax78/breezynotes-auth --file ./build/auth/dockerfile .
      - docker build -t zitrax78/breezynotes-blocknote --file ./build/blocknote/dockerfile .
      - docker build -t zitrax78/breezynotes-redis --file ./build/redis/dockerfile .
  build gateway:
    aliases:
      - build-gateway
    cmds:
      - docker build -t zitrax78/breezynotes-gateway --file ./build/gateway/dockerfile .
  build auth:
    aliases:
      - build-auth
    cmds:
      - docker build -t zitrax78/breezynotes-auth --file ./build/auth/dockerfile .
  build blocknote:
    aliases:
      - build-blocknote
    cmds:
      - docker build -t zitrax78/breezynotes-blocknote --file ./build/blocknote/dockerfile .
  build redis:
    aliases:
      - build-redis
    cmds:
      - docker build -t zitrax78/breezynotes-redis --file ./build/redis/dockerfile .

  build migrator:
    aliases:
      - build-migrator
    cmd: go build -o ./build/deploy/migrator.exe ./cmd/migrator
  migrations up:
    aliases:
      - mig-up
    cmd: ./build/deploy/migrator.exe --type up
  migrations down:
    aliases:
      - mig-down
    cmd: ./build/deploy/migrator.exe --type down

  generate proto:
    aliases:
      - gen
    cmds:
      - protoc --proto_path pkg/protos/proto/ -I proto pkg/protos/proto/auth.proto --go_out pkg/protos/proto/gen --go_opt=paths=source_relative --go-grpc_out=pkg/protos/proto/gen --go-grpc_opt=paths=source_relative
      - protoc --proto_path pkg/protos/proto/ -I proto pkg/protos/proto/notes.proto --go_out pkg/protos/proto/gen --go_opt=paths=source_relative --go-grpc_out=pkg/protos/proto/gen --go-grpc_opt=paths=source_relative
      - protoc --proto_path pkg/protos/proto/ -I proto pkg/protos/proto/redis.proto --go_out pkg/protos/proto/gen --go_opt=paths=source_relative --go-grpc_out=pkg/protos/proto/gen --go-grpc_opt=paths=source_relative
      - protoc --proto_path pkg/protos/proto/ -I proto pkg/protos/proto/domain.proto --go_out pkg/protos/proto/gen --go_opt=paths=source_relative --go-grpc_out=pkg/protos/proto/gen --go-grpc_opt=paths=source_relative

  compose up:
    aliases:
      - compose-up
    cmd: docker compose -f ./build/deploy/docker-compose.yml up -d
  compose down:
    aliases:
      - compose-down
    cmd: docker compose -f ./build/deploy/docker-compose.yml down
  compose rest:
    aliases:
      - compose-rest
    cmds:
      - docker compose -f ./build/deploy/docker-compose.yml down
      - docker compose -f ./build/deploy/docker-compose.yml up -d
  compose up repl:
    aliases:
      - compose-up-repl
    cmd: docker compose -f ./build/deploy/docker-compose.repl.yml up -d
  compose down repl:
    aliases:
      - compose-down-repl
    cmd: docker compose -f ./build/deploy/docker-compose.repl.yml down
  compose up db:
    aliases:
      - compose-up-db
    cmd: docker compose -f ./build/deploy/docker-compose.db.yml up -d
  compose down db:
    aliases:
      - compose-down-db
    cmd: docker compose -f ./build/deploy/docker-compose.db.yml down

  run all:
    aliases:
      - run-all
    cmds:
      -  go run ./cmd/blocknote --cfg ./local-config/blocknote.yaml
      -  go run ./cmd/redis --cfg ./local-config/redis.yaml
      -  go run ./cmd/gateway --cfg ./local-config/gateway.yaml
      -  go run ./cmd/auth --cfg ./local-config/auth.yaml

  docx:
    aliases:
      - docx
    cmds:
      - swag init --dir ./cmd/gateway,./internal/gateway/net/,./views,./pkg/protos/proto/gen --output ./docs